version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

# Run the following command to start the services:
# docker-compose up, docker-compose up -d (detached mode)

# stop the services:
# docker-compose down